version: '3'

services:
  banking-service:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://banking_db_server:5432/banking_db
      DB_USER_NAME: postgres
      DB_PASSWORD: admin
    restart: always
    depends_on:
      banking_db_server:
        condition: service_healthy

  banking_db_server:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banking_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
